"""Primary public API for TeXSmith."""

from __future__ import annotations

from texsmith.api import (
    ConversionBundle,
    ConversionRequest,
    ConversionResponse,
    ConversionService,
    Document,
    DocumentRenderOptions,
    HeadingLevel,
    LaTeXFragment,
    RenderSettings,
    SlotAssignment,
    TemplateOptions,
    TemplateRenderResult,
    TemplateSession,
    TitleStrategy,
    classify_input_source,
    convert_documents,
    get_template,
    resolve_heading_level,
)
from texsmith.core.bibliography import (
    BibliographyCollection,
    BibliographyIssue,
    DoiBibliographyFetcher,
    DoiLookupError,
    bibliography_data_from_string,
)
from texsmith.core.config import BookConfig, LaTeXConfig
from texsmith.core.context import AssetRegistry, DocumentState, RenderContext
from texsmith.core.rules import RenderPhase, renders
from texsmith.core.templates import (
    DEFAULT_TEMPLATE_LANGUAGE,
    TemplateBinding,
    TemplateError,
    TemplateRuntime,
    TemplateSlot,
    WrappableTemplate,
    build_template_overrides,
    copy_template_assets,
    load_template,
    load_template_runtime,
    resolve_template_language,
)


__all__ = [
    "DEFAULT_TEMPLATE_LANGUAGE",
    "AssetRegistry",
    "BibliographyCollection",
    "BibliographyIssue",
    "BookConfig",
    "ConversionBundle",
    "ConversionRequest",
    "ConversionResponse",
    "ConversionService",
    "Document",
    "DocumentRenderOptions",
    "DocumentState",
    "DoiBibliographyFetcher",
    "DoiLookupError",
    "HeadingLevel",
    "LaTeXConfig",
    "LaTeXFragment",
    "RenderContext",
    "RenderPhase",
    "RenderSettings",
    "SlotAssignment",
    "TemplateBinding",
    "TemplateError",
    "TemplateOptions",
    "TemplateRenderResult",
    "TemplateRuntime",
    "TemplateSession",
    "TemplateSlot",
    "TitleStrategy",
    "WrappableTemplate",
    "bibliography_data_from_string",
    "build_template_overrides",
    "classify_input_source",
    "convert_documents",
    "copy_template_assets",
    "get_template",
    "load_template",
    "load_template_runtime",
    "renders",
    "resolve_heading_level",
    "resolve_template_language",
]
