nav:
  - getting-started.md
  - front-matter.md
  - metadata.md
  - extensions.md
  - fonts.md
  - fragments/
  - features/
  - templates/
  - plumbing/
  - MkDocs Integration: mkdocs.md
  - tectonic.md
  - troubleshooting.md
