"""Compatibility layer for the refactored LaTeX template helpers."""

from __future__ import annotations

from texsmith.adapters.latex.templates import (
    BaseTemplate,
    DEFAULT_TEMPLATE_LANGUAGE,
    LATEX_HEADING_LEVELS,
    ResolvedAsset,
    TemplateAsset,
    TemplateBinding,
    TemplateError,
    TemplateInfo,
    TemplateManifest,
    TemplateRuntime,
    TemplateSlot,
    WrappableTemplate,
    build_template_overrides,
    coerce_base_level,
    copy_template_assets,
    extract_base_level_override,
    extract_language_from_front_matter,
    load_template,
    load_template_runtime,
    normalise_template_language,
    resolve_template_binding,
    resolve_template_language,
)

__all__ = [
    "BaseTemplate",
    "DEFAULT_TEMPLATE_LANGUAGE",
    "LATEX_HEADING_LEVELS",
    "ResolvedAsset",
    "TemplateAsset",
    "TemplateBinding",
    "TemplateError",
    "TemplateInfo",
    "TemplateManifest",
    "TemplateRuntime",
    "TemplateSlot",
    "WrappableTemplate",
    "build_template_overrides",
    "coerce_base_level",
    "copy_template_assets",
    "extract_base_level_override",
    "extract_language_from_front_matter",
    "load_template",
    "load_template_runtime",
    "normalise_template_language",
    "resolve_template_binding",
    "resolve_template_language",
]
