"""Helpers for configuring latexmk commands and RC files."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import shlex
import shutil
from typing import Any

from texsmith.adapters.latex import pyxindy


@dataclass(slots=True)
class LatexmkEngine:
    """Normalised latexmk engine invocation."""

    command: list[str]
    pdf_mode: int


def _perl_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace("'", "\\'")


def _pdf_mode_from_command(command: str) -> int:
    lowered = Path(command).name.lower()
    if lowered.endswith("xelatex"):
        return 5
    if lowered.endswith("lualatex"):
        return 4
    return 1


def normalise_engine_command(engine: str | None, *, shell_escape: bool) -> LatexmkEngine:
    """Return latexmk engine tokens and pdf mode derived from the provided string."""
    tokens = shlex.split(engine.strip()) if engine else []
    if not tokens:
        tokens = ["pdflatex"]

    if shell_escape and not any(token in {"-shell-escape", "--shell-escape"} for token in tokens):
        tokens.append("--shell-escape")

    pdf_mode = _pdf_mode_from_command(tokens[0])
    return LatexmkEngine(command=tokens, pdf_mode=pdf_mode)


def latexmk_pdf_flag(pdf_mode: int) -> str:
    """Return the latexmk flag required for the requested pdf mode."""
    if pdf_mode == 4:
        return "-pdflua"
    if pdf_mode == 5:
        return "-pdfxe"
    return "-pdf"


def build_engine_command(engine: LatexmkEngine) -> str:
    """Construct the pdflatex command string used by latexmk."""
    return shlex.join([*engine.command, "%O", "%S"])


def normalise_index_engine(candidate: Any) -> str:
    """Resolve the effective index engine from template context or availability."""
    if isinstance(candidate, str):
        stripped = candidate.strip().lower()
        if stripped in {"pyxindy", "texindy", "makeindex"}:
            if stripped == "pyxindy" and not pyxindy.is_available():
                stripped = "texindy" if shutil.which("texindy") else "makeindex"
            return stripped
    if pyxindy.is_available():
        return "pyxindy"
    return "texindy" if shutil.which("texindy") else "makeindex"


def _engine_variable(pdf_mode: int) -> str:
    if pdf_mode == 5:
        return "xelatex"
    if pdf_mode == 4:
        return "lualatex"
    return "pdflatex"


def build_latexmkrc_content(
    *,
    root_filename: str,
    engine: str | None,
    requires_shell_escape: bool,
    bibliography: bool,
    index_engine: str | None = None,
    has_index: bool = False,
    has_glossary: bool = False,
) -> str:
    """Produce a latexmkrc payload matching the selected template features."""
    engine_config = normalise_engine_command(engine, shell_escape=requires_shell_escape)
    command_string = build_engine_command(engine_config)
    engine_var = _engine_variable(engine_config.pdf_mode)
    safe_root = _perl_escape(root_filename or "texsmith-output")

    lines = [
        "# Auto-generated by texsmith\n",
        f"$root_filename = '{safe_root}';\n",
        f"$pdf_mode = {engine_config.pdf_mode};\n",
        f"${engine_var} = '{_perl_escape(command_string)}';\n",
    ]

    if bibliography:
        lines.extend(
            [
                "$bibtex_use = 2;\n",
                "$biber = 'biber %O %B';\n",
                "$clean_ext .= ' %R.run.xml %R.blg';\n",
            ]
        )

    if has_index:
        index_var = normalise_index_engine(index_engine)
        if index_var == "pyxindy":
            makeindex = pyxindy.latexmk_makeindex_command()
        else:
            makeindex = "texindy %O -o %D %S" if index_var == "texindy" else "makeindex %O -o %D %S"
        lines.append(f"$makeindex = '{_perl_escape(makeindex)}';\n")

    if has_glossary:
        glossaries_cmd = pyxindy.latexmk_makeglossaries_command()
        lines.extend(
            [
                "add_cus_dep('glo', 'gls', 0, 'run_makeglossaries');\n",
                "add_cus_dep('acn', 'acr', 0, 'run_makeglossaries');\n",
                "\n",
                "sub run_makeglossaries {\n",
                "  my ($base) = @_;\n",
                f'  my $cmd = "{_perl_escape(glossaries_cmd)}";\n',
                "  return system($cmd);\n",
                "}\n",
            ]
        )

    return "".join(lines)


__all__ = [
    "LatexmkEngine",
    "build_engine_command",
    "build_latexmkrc_content",
    "latexmk_pdf_flag",
    "normalise_engine_command",
    "normalise_index_engine",
]
