"""TeXSmith intermediate representation (IR).

The semantic, backend-agnostic document tree consumed by every writer and
produced by every reader. See :mod:`texsmith.ir.nodes` for the sealed
``Block`` / ``Inline`` hierarchy and the transverse-state map, and
:mod:`texsmith.ir.visitor` for traversal utilities.
"""

from __future__ import annotations

from texsmith.ir.nodes import (
    Admonition,
    Alignment,
    AnyNode,
    Block,
    BlockQuote,
    BulletList,
    CitationMode,
    Cite,
    Code,
    CodeBlock,
    DefinitionItem,
    DefinitionList,
    Div,
    Document,
    Emph,
    Figure,
    Header,
    Highlight,
    HorizontalRule,
    Image,
    IndexEntry,
    Inline,
    Keystroke,
    LineBreak,
    Link,
    ListStyle,
    MarginNote,
    MarginSide,
    Math,
    Node,
    Note,
    OrderedList,
    Para,
    Plain,
    ProgressBar,
    Quoted,
    RawBlock,
    RawInline,
    SmallCaps,
    SoftBreak,
    Space,
    Span,
    Str,
    Strikeout,
    Strong,
    Subscript,
    Superscript,
    Table,
    TexLogo,
    Underline,
)
from texsmith.ir.visitor import (
    NodeVisitor,
    children,
    iter_child_fields,
    map_tree,
    walk,
)


__all__ = [
    "Admonition",
    "Alignment",
    "AnyNode",
    "Block",
    "BlockQuote",
    "BulletList",
    "CitationMode",
    "Cite",
    "Code",
    "CodeBlock",
    "DefinitionItem",
    "DefinitionList",
    "Div",
    "Document",
    "Emph",
    "Figure",
    "Header",
    "Highlight",
    "HorizontalRule",
    "Image",
    "IndexEntry",
    "Inline",
    "Keystroke",
    "LineBreak",
    "Link",
    "ListStyle",
    "MarginNote",
    "MarginSide",
    "Math",
    "Node",
    "NodeVisitor",
    "Note",
    "OrderedList",
    "Para",
    "Plain",
    "ProgressBar",
    "Quoted",
    "RawBlock",
    "RawInline",
    "SmallCaps",
    "SoftBreak",
    "Space",
    "Span",
    "Str",
    "Strikeout",
    "Strong",
    "Subscript",
    "Superscript",
    "Table",
    "TexLogo",
    "Underline",
    "children",
    "iter_child_fields",
    "map_tree",
    "walk",
]
